nome = str(input('\nDigite seu nome completo: ')).strip()
print('\nAnalisando seu nome...\n')
print('O seu nome em letras maiúsculas é: {}'.format(nome.upper()))
print('O seu nome em letras minúsculas é: {}'.format(nome.lower()))
print('O seu nome tem {} letras'.format(len(nome) - nome.count(' ')))
#print('Seu primeiro nome tem {} letras.'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.\n'.format(separa[1], len(separa[1])))